### PR TITLE
Update IE Web Driver to v2.49

### PR DESCRIPTION
**Pull request by FlorianDecker**
Hi,

this pull request is for an older version of IE Driver. This version fixes some issues for us, while the subsequent versions sadly introduce new ones. I cant create a pull request for a new branch, would it be possible for you to merge the changes into a seperate branch and add this version to the nuget package?

Thanks a lot!

Regards,
Florian

### CODE REVIEW

**Comment by SeriousM** [comment]
Hi Florian,

the current available packages are:
WebDriver.IEDrive... 2.44.0, 2.53.0, 2.53.1
which means that the 2.49 would just be another version I can release.
That's no problem and is only a nuget-related task, not necessarily a git(hub) task.
If that's ok, I will release the 2.49 as well as the 3.0.0.

**Comment by FlorianDecker** [comment]
Thats perfect, thank you very much :)

**Comment by SeriousM** [comment]
Alright, both released. Sorry that I didn't used your pull request, but I'm sure there will be a next version that needs to released :)

**Comment by FlorianDecker** [comment]
Thank you :)

**Pull request closed without merging**
